(function(root){'use strict';
const catalog=[
{id:'cove-001',title:'Someone found the Cove',destination:'Enter the Cove',kind:'cove',panels:[['walk','Midknight had gone for a walk.'],['peek','Something caught his attention.'],['discover','He found somewhere worth staying.'],['home','A few things were missing. Apparently, that was our part.']]},
{id:'festival-001',title:'The neighbors had made plans',destination:'Visit the Festival',kind:'festival',panels:[['peek','Something was happening nearby.'],['festival','The neighbors had made plans.'],['sleep','Everyone was participating. In their own way.'],['party','There was room for us, too.']]},
{id:'resort-001',title:'Room for a few more',destination:'Visit the resort',kind:'resort',panels:[['walk','The path carried on around the coast.'],['cottages','There were places to stay. Just nobody staying.'],['peek','Midknight inspected the accommodation.'],['home','He left the paperwork to us.']]},
{id:'cafe-001',title:'Something warm',destination:'Visit Catmint Café',kind:'cafe',panels:[['cafe','A little place by the water.'],['peek','Someone had noticed the counter.'],['home','We might need a bigger menu.']]}
];let active=null;
function state(a){const g=a.game();if(!g.coveStories||g.coveStories.version!==1)g.coveStories={version:1,entries:{}};return g.coveStories;}
function paint(cv,kind,beat,index,a){const c=cv.getContext('2d');cv.width=600;cv.height=340;const box=(x,y,w,h,col)=>{c.fillStyle=col;c.fillRect(x,y,w,h);},oval=(x,y,rx,ry,col)=>{c.fillStyle=col;c.beginPath();c.ellipse(x,y,rx,ry,0,0,7);c.fill();};box(0,0,600,340,'#a8d6dc');oval(455,56,25,25,'#fff3cb');oval(80,40,55,10,'#dfede7');box(0,123,600,100,'#78b9c1');box(0,202,600,138,'#b5cb91');box(0,204,600,12,'#ded3a6');for(let i=0;i<11;i++)box(i*63,164+(i%2)*9,29,2,'#d6eee0');
for(let i=0;i<14;i++){let x=(i*97)%600,y=245+(i*29)%85;box(x,y,3,12,'#8ba871');box(x+7,y-3,3,14,'#8ba871');}
if(beat==='cottages'||kind==='resort'){for(let i=0;i<3;i++){box(50+i*182,167,130,81,'#f5e5c0');c.fillStyle='#72947e';c.beginPath();c.moveTo(40+i*182,172);c.lineTo(115+i*182,125);c.lineTo(190+i*182,172);c.fill();box(100+i*182,205,26,43,'#947951');}}
if(kind==='festival'){c.strokeStyle='#796b4a';c.lineWidth=3;c.beginPath();c.moveTo(20,70);c.quadraticCurveTo(300,160,580,70);c.stroke();for(let i=0;i<10;i++){let x=38+i*55,y=78+Math.sin(i/9*Math.PI)*35;c.fillStyle=['#d9a271','#e7cc81','#8cab96'][i%3];c.beginPath();c.moveTo(x,y);c.lineTo(x+23,y+4);c.lineTo(x+9,y+29);c.fill();}if(index>0){a.cat(c,{coatKey:'ginger',markSeed:22,pose:'loafing'},160,275,1.2,0);a.cat(c,{coatKey:'greywhite',markSeed:31,pose:'loafing'},435,280,1.15,0);}}
if(kind==='cafe'){box(345,153,206,130,'#eee0b9');box(330,148,236,30,'#79947e');box(354,210,185,42,'#8c7555');oval(460,211,16,8,'#fff5dd');}
if(kind==='cove'){box(410,195,105,10,'#ad8d62');box(424,205,7,39,'#947451');box(494,205,7,39,'#947451');c.fillStyle='#514b35';c.font='15px Georgia';c.textAlign='center';c.fillText('CATMINT COVE',462,191);}
const pose=beat==='sleep'||beat==='home'?'sleeping':beat==='walk'?'exploring':'loafing';a.cat(c,{coatKey:'midknight',markSeed:4242,mascot:true,pose},beat==='walk'?220:300,295,1.85,0);
if(beat==='peek'){for(let i=0;i<13;i++){c.strokeStyle=i%2?'#819b64':'#99b378';c.lineWidth=9;c.beginPath();c.moveTo(223+i*13,340);c.quadraticCurveTo(230+i*13,295,212+i*13,259+(i%3)*13);c.stroke();}}
}
function open(id,a,done,replay=false){const story=catalog.find(s=>s.id===id);if(!story){done?.();return;}if(active)return;const st=state(a);let entry=st.entries[id];if(!replay&&entry&&(entry.status==='complete'||entry.status==='skipped')){done?.();return;}
if(!entry){entry=st.entries[id]={panel:0,status:'reading',discoveredAt:Date.now()};a.save();}let panel=replay?0:Math.max(0,Math.min(story.panels.length-1,entry.panel||0));const previous=document.activeElement;const dlg=document.createElement('dialog');dlg.className='cove-comic';dlg.setAttribute('aria-label',story.title);dlg.innerHTML='<header><div><small>COVE STORIES</small><h2></h2></div><button type="button" class="comic-skip"></button></header><div class="comic-panels"></div><footer><span class="comic-position" aria-live="polite"></span><button type="button" class="comic-next"></button></footer>';dlg.querySelector('h2').textContent=story.title;dlg.querySelector('.comic-skip').textContent=replay?'Close story':'Skip intro';document.body.append(dlg);active=dlg;const grid=dlg.querySelector('.comic-panels');
function finish(skipped){if(!replay){entry.status=skipped?'skipped':'complete';entry.panel=panel;entry.finishedAt=Date.now();a.save();}dlg.close();dlg.remove();active=null;previous?.focus?.({preventScroll:true});done?.();}
function render(){grid.replaceChildren();for(let i=0;i<=panel;i++){const f=document.createElement('figure'),cv=document.createElement('canvas'),cap=document.createElement('figcaption');cv.setAttribute('aria-hidden','true');cap.textContent=story.panels[i][1];f.append(cv,cap);grid.append(f);paint(cv,story.kind,story.panels[i][0],i,a);}dlg.querySelector('.comic-position').textContent=(panel+1)+' / '+story.panels.length;dlg.querySelector('.comic-next').textContent=panel===story.panels.length-1?(replay?'Back to Journal':story.destination):'Tap to continue';grid.lastElementChild?.scrollIntoView({block:'nearest',behavior:'instant'});}
function next(){if(panel===story.panels.length-1){finish(false);return;}panel++;if(!replay){entry.panel=panel;a.save();}render();}dlg.querySelector('.comic-next').onclick=next;grid.onclick=next;dlg.querySelector('.comic-skip').onclick=()=>finish(true);dlg.addEventListener('cancel',e=>{e.preventDefault();finish(true);});dlg.showModal();render();dlg.querySelector('.comic-next').focus();}
function journal(container,a){if(!container)return;const entries=state(a).entries;const section=document.createElement('section');section.className='comic-library';const h=document.createElement('h3');h.textContent='Cove Stories';section.append(h);const intro=document.createElement('p');intro.className='muted';intro.textContent='Little beginnings, kept here. Discover places in the Cove to add their stories.';section.append(intro);for(const [i,s] of catalog.entries()){const b=document.createElement('button');b.className='btn';b.textContent=String(i+1).padStart(3,'0')+' · '+s.title;b.disabled=!entries[s.id];if(!entries[s.id])b.textContent+=' · Not discovered';b.onclick=()=>open(s.id,a,null,true);section.append(b);}container.append(section);}
root.CoveStories={open,journal,catalog,isOpen:()=>!!active};
})(globalThis);
