(function(root){'use strict';
const guests=[{id:'poppy',name:'Poppy',coatKey:'calico',markSeed:74001,recipe:'tea',ingredient:'catmint',title:'Something warm after a swim',line:'A cup of Catmint Cloud would make the coast feel like home.'},{id:'otis',name:'Otis',coatKey:'ginger',markSeed:74002,recipe:'coffee',ingredient:'coffee',title:'A slow morning by the sea',line:'Coastal Coffee, a quiet room, and nowhere to hurry.'},{id:'juniper',name:'Juniper',coatKey:'greywhite',markSeed:74003,recipe:'carrot_crunch',ingredient:'carrot',title:'A little taste of the garden',line:'Carrot Crunch sounds just right after a coastal walk.'}];
function state(g){if(!g.guestStories)g.guestStories={version:1,active:null,memories:[],flowerBox:false};return g.guestStories;}
function eligible(g,id){const d=guests.find(x=>x.id===id);return !!d&&!!g.cafe?.unlocked&&g.cafe.discovered?.includes(d.recipe)&&g.resort?.cottages?.some(c=>c.built&&!c.job);}
function sync(g){const s=state(g),r=s.active,d=r&&guests.find(x=>x.id===r.guest);if(d&&r.stage==='ingredients'&&(g.homestead?.stock?.[d.ingredient]||0)>0)r.stage='serve';return s;}
function accept(g,id,now=Date.now()){const s=state(g);if(s.active||s.memories.some(m=>m.guest===id)||!eligible(g,id))return false;s.active={id:'welcome-'+id,guest:id,stage:'ingredients',acceptedAt:now};sync(g);return true;}
function served(g,items,at){const s=sync(g),r=s.active,d=r&&guests.find(x=>x.id===r.guest);if(!d||!['ingredients','serve'].includes(r.stage)||at<r.acceptedAt||!items.includes(d.recipe))return false;r.stage='return';r.servedAt=at;return true;}
function booking(g,capacity,at){const s=state(g),r=s.active,d=r&&guests.find(x=>x.id===r.guest);if(!d||r.stage!=='return'||at<r.servedAt)return null;r.stage='staying';r.bookedAt=at;return {kind:capacity>1?'friends':'solo',name:d.name,requestId:r.id,members:Array.from({length:capacity},(_,i)=>({coatKey:i?'cream':d.coatKey,markSeed:d.markSeed+i,age:'adult'}))};}
function checkout(g,party,at){const s=state(g),r=s.active;if(!r||r.stage!=='staying'||party?.requestId!==r.id||at<r.bookedAt)return false;if(!s.memories.some(m=>m.id===r.id))s.memories.push({id:r.id,guest:r.guest,at});s.active=null;if(s.memories.length>=3){s.flowerBox=true;if(g.cafe)g.cafe.guestFlowerBox=true;}g.coveStories||={version:1,entries:{}};g.coveStories.entries['guest-001']||={status:'complete',panel:3,discoveredAt:at,finishedAt:at};return true;}
function displaced(g,party){const s=state(g),r=s.active;if(r?.stage==='staying'&&party?.requestId===r.id){r.stage='return';delete r.bookedAt;}}
function summary(g){const s=sync(g),r=s.active,d=r&&guests.find(x=>x.id===r.guest);return {s,r,d,text:d?({ingredients:'Grow '+d.ingredient+' in Cove Garden',serve:'Serve '+(root.CoveCafeEngine?.recipes.find(x=>x.id===d.recipe)?.name||d.recipe)+' at the café',return:d.name+' will take the next available room',staying:d.name+' is enjoying a stay — a memory follows at checkout'}[r.stage]):s.flowerBox?'Your guest flower box is blooming':'A familiar face is waiting for a welcome'};}
root.CoveGuestStories={guests,state,sync,eligible,accept,served,booking,checkout,displaced,summary};
})(globalThis);
