(function(){
window.drawHalloweenAccessory=function(g,kind,P){if(!['pumpkinhat','witchhat'].includes(kind))return false;g.save();g.translate(P.hx,P.hy-P.hr*.85);g.scale(P.hr/13,P.hr/13);g.lineJoin='round';g.lineWidth=1.2;
if(kind==='witchhat'){g.fillStyle='#40364e';g.strokeStyle='#2a2934';g.beginPath();g.ellipse(0,0,19,4,0,0,7);g.fill();g.stroke();g.beginPath();g.moveTo(-12,-1);g.lineTo(-4,-27);g.quadraticCurveTo(0,-36,12,-27);g.lineTo(5,-27);g.lineTo(12,-1);g.closePath();g.fill();g.stroke();g.fillStyle='#ba763d';g.beginPath();g.moveTo(-10,-7);g.lineTo(10,-7);g.lineTo(12,-2);g.lineTo(-12,-2);g.fill();g.strokeStyle='#efc86c';g.strokeRect(-2,-7,5,5);
}else{g.strokeStyle='#93532e';for(const [x,rx,col] of [[-7,7,'#c87139'],[7,7,'#c87139'],[0,8,'#e39749']]){g.fillStyle=col;g.beginPath();g.ellipse(x,-7,rx,10,0,0,7);g.fill();g.stroke();}g.strokeStyle='#637544';g.lineWidth=3;g.beginPath();g.moveTo(0,-16);g.quadraticCurveTo(-3,-22,2,-22);g.stroke();g.fillStyle='#6f894e';g.beginPath();g.ellipse(6,-18,6,2.5,-.4,0,7);g.fill();}g.restore();return true;};
window.covePumpkin=function(g,x,y,s=1){g.save();g.translate(x,y);g.scale(s,s);g.fillStyle='#263c3330';g.beginPath();g.ellipse(0,2,25,7,0,0,7);g.fill();for(const [x,rx,col] of [[-10,12,'#bc6534'],[10,12,'#ca7439'],[0,13,'#e29545']]){g.fillStyle=col;g.strokeStyle='#9e5a34';g.lineWidth=1;g.beginPath();g.ellipse(x,-16,rx,18,0,0,7);g.fill();g.stroke();}g.fillStyle='#fce1a0';for(const x of [-9,5]){g.beginPath();g.moveTo(x,-23);g.lineTo(x+5,-17);g.lineTo(x-2,-17);g.fill();}g.beginPath();g.moveTo(-9,-11);g.quadraticCurveTo(0,1,10,-11);g.quadraticCurveTo(0,-6,-9,-11);g.fill();g.strokeStyle='#637149';g.lineWidth=5;g.beginPath();g.moveTo(0,-32);g.quadraticCurveTo(-3,-40,3,-42);g.stroke();g.restore();};
})();
// Seasonal decor shares the game's canvas renderer and placement system.
window.coveSpookyTree=function(g,x,y,s=1){g.save();g.translate(x,y);g.scale(s,s);g.fillStyle='#333e3330';g.beginPath();g.ellipse(0,0,38,10,0,0,7);g.fill();g.strokeStyle='#635044';g.lineCap='round';g.lineJoin='round';g.lineWidth=10;g.beginPath();g.moveTo(-12,0);g.quadraticCurveTo(10,-45,0,-122);g.moveTo(0,-65);g.lineTo(-31,-90);g.lineTo(-42,-127);g.moveTo(0,-87);g.lineTo(32,-109);g.lineTo(44,-141);g.stroke();g.lineWidth=5;g.beginPath();g.moveTo(-30,-90);g.lineTo(-58,-101);g.moveTo(32,-109);g.lineTo(64,-117);g.moveTo(1,-108);g.lineTo(-13,-142);g.stroke();g.strokeStyle='#c6b995';g.lineWidth=1;g.beginPath();g.moveTo(31,-108);g.lineTo(31,-72);g.stroke();const glow=g.createRadialGradient(31,-61,2,31,-61,34);glow.addColorStop(0,'#f8c36370');glow.addColorStop(1,'#f8c36300');g.fillStyle=glow;g.fillRect(-4,-96,70,70);g.fillStyle='#e9ba67';g.strokeStyle='#715843';g.lineWidth=2;g.fillRect(24,-73,14,22);g.strokeRect(24,-73,14,22);g.restore();};
window.coveBatBunting=function(g,t,x,y,s=1){g.save();g.translate(x,y);g.scale(s,s);g.strokeStyle='#78614a';g.lineWidth=5;for(const px of [-80,80]){g.beginPath();g.moveTo(px,0);g.lineTo(px,-90);g.stroke();}g.strokeStyle='#aa9877';g.lineWidth=1.5;g.beginPath();g.moveTo(-80,-86);g.quadraticCurveTo(0,-52,80,-86);g.stroke();for(let i=0;i<5;i++){const px=-60+i*30,py=-78+Math.sin(i/4*Math.PI)*12;g.save();g.translate(px,py);g.rotate(Math.sin(t*.7+i)*.05);g.fillStyle='#493d50';g.beginPath();g.moveTo(0,8);g.lineTo(-14,-2);g.quadraticCurveTo(-7,0,-8,7);g.lineTo(-3,5);g.lineTo(-2,0);g.lineTo(0,3);g.lineTo(2,0);g.lineTo(3,5);g.lineTo(8,7);g.quadraticCurveTo(7,0,14,-2);g.closePath();g.fill();g.restore();}g.restore();};

// A local-calendar greeting, kept once per year in the player's journal.
window.CoveHalloween={
 title:'Happy Halloween, Cove keeper!',
 message:'The lanterns are glowing, the hats are a little crooked, and Midknight is keeping watch. Dress up, make the Cove your kind of spooky, and enjoy a cozy October night. All Halloween decorations and hats are free in the shop.',
 isDay(date=new Date()){return date.getMonth()===9&&date.getDate()===31;},
 remember(g,date=new Date()){if(!this.isDay(date))return false;const year=date.getFullYear();g.halloweenGreetings||={};if(g.halloweenGreetings[year])return false;g.halloweenGreetings[year]=date.getTime();return true;},
 visible(g,date=new Date()){return this.isDay(date)||Object.keys(g.halloweenGreetings||{}).length>0;},
 journal(root,g,openShop){if(!this.visible(g))return;const card=document.createElement('section');card.className='gs-journal';const title=document.createElement('h3');title.textContent=this.title;const message=document.createElement('p');message.textContent=this.message;const button=document.createElement('button');button.className='btn';button.textContent='Explore free Halloween decor';button.onclick=openShop;card.append(title,message,button);root.append(card);}
};
