(function(root){'use strict';let sheet,timer,frame,lastFrame=0,api,signature='';
function render(){if(!sheet||sheet.hidden)return;const E=root.CoveResortEngine,g=api.game(),s=E.init(g),i=s.selected,c=s.cottages[i],z=E.stats(c),next=E.STAGES[c.stage+1];
const sig=JSON.stringify([s.view,i,g.shells,s.completedStays,c.stage,c.bed,c.built,c.guest?.party.name]);if(sig===signature)return;signature=sig;
sheet.querySelector('.rs-wallet').textContent=Math.floor(g.shells)+' Shells';sheet.querySelector('.rs-map-label').textContent=s.view==='inside'?'Inside cottage '+(i+1):'A little more room by the sea';
const info=sheet.querySelector('.rs-chrome');info.innerHTML=`<span class="rs-kicker">${c.built?'YOUR RESORT':'ROOM TO GROW'}</span><h3>${c.built?E.STAGES[c.stage].name:'Cottage '+(i+1)}</h3><p>${c.built?'Guests arrive, rest and check out automatically. Your upgrades take effect for the next arrival.':'A furnished cottage, ready for its first visitors. Open it and the resort looks after each stay.'}</p><div class="rs-summary">${s.completedStays} stays · ${s.revenue} Shells earned</div>`;
function button(label,action,disabled=false){const b=document.createElement('button');b.className='btn';b.textContent=label;b.disabled=disabled;b.onclick=()=>{action();api.save();signature='';render();draw();};info.append(b);}
if(!c.built){const cost=E.BUILD_COST[i];button(i===0?'Open first cottage · Free':'Open cottage · '+cost+' Shells',()=>E.buildCottage(g,i),g.shells<cost||(i>0&&!s.cottages[i-1].built));if(i>0&&!s.cottages[i-1].built){const p=document.createElement('p');p.textContent='Open the previous cottage first.';info.append(p);}}
else{button(s.view==='inside'?'Back to resort map':'Look inside',()=>s.view=s.view==='inside'?'outside':'inside');const p=document.createElement('p');p.className='rs-income';p.textContent=z.capacity+' guest'+(z.capacity>1?'s':'')+' · '+z.payout*z.capacity+' Shells per stay · '+Math.round(z.stayMs/1000)+' seconds';info.append(p);if(next)button('Upgrade cottage · '+next.cost+' Shells',()=>E.upgradeCottage(g,i),g.shells<next.cost);if(c.bed<2)button('Upgrade beds · '+120*(c.bed+1)+' Shells',()=>E.upgradeBed(g,i),g.shells<120*(c.bed+1));}
const note=document.createElement('small');note.textContent='Guests keep checking in while you are away, for up to 8 hours. No manual cleaning or check-in.';info.append(note);
const plots=sheet.querySelector('.rs-plots');plots.hidden=s.view==='inside';plots.querySelectorAll('button').forEach((b,j)=>{b.setAttribute('aria-pressed',String(j===i));b.setAttribute('aria-label',(s.cottages[j].built?'Inspect':'Open')+' cottage '+(j+1));});}
function draw(){if(!sheet||sheet.hidden||document.hidden)return;const cv=sheet.querySelector('canvas'),r=cv.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(!w||!h)return;if(cv.width!==w||cv.height!==h){cv.width=w;cv.height=h;}const ctx=cv.getContext('2d');ctx.setTransform(w/960,0,0,h/640,0,0);const s=root.CoveResortEngine.init(api.game());root.CoveResortScene(ctx,{view:s.view,cottages:s.cottages,selected:s.selected,t:matchMedia('(prefers-reduced-motion: reduce)').matches?0:performance.now(),a:api});}
root.CoveResortView={open(a){this.stop();api=a;if(!sheet){sheet=document.createElement('section');sheet.id='neo-resort';sheet.className='sheet neo-resort-screen';sheet.setAttribute('aria-label','Cove Resort');sheet.innerHTML='<header class="rs-top"><button class="btn rs-close">‹ Cove</button><div><span class="rs-kicker">A PLACE TO STAY</span><h2>Cove Resort</h2></div><span class="rs-wallet"></span></header><div class="rs-layout"><div class="rs-world"><p class="rs-map-label"></p><div class="rs-scene-wrap"><canvas width="960" height="640" aria-label="Seaside resort map"></canvas><div class="rs-plots"></div></div><p class="rs-map-help">Choose a cottage to open it, look inside or upgrade.</p></div><aside class="rs-chrome"></aside></div>';document.getElementById('app').append(sheet);a.register(sheet);for(const [i,p] of root.CoveResortScene.slots.entries()){const b=document.createElement('button');b.style.cssText=`left:${p.x/9.6}%;top:${(p.y-12)/6.4}%;width:${p.w/9.6}%;height:${(p.h+20)/6.4}%`;b.onclick=()=>{const s=root.CoveResortEngine.init(api.game());s.selected=i;api.save();signature='';render();draw();};sheet.querySelector('.rs-plots').append(b);}sheet.querySelector('.rs-close').onclick=()=>{this.stop();api.close();};}sheet.hidden=false;signature='';root.CoveResortEngine.settle(a.game());a.save();render();draw();timer=setInterval(()=>{if(sheet.hidden){this.stop();return;}if(document.hidden)return;root.CoveResortEngine.settle(api.game());render();},1000);const tick=t=>{if(sheet.hidden)return;if(t-lastFrame>66){draw();lastFrame=t;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);},stop(){clearInterval(timer);cancelAnimationFrame(frame);}};
})(globalThis);
