(function(root){'use strict';let sheet,timer,frame,lastFrame=0,api,signature='',panelMode='',resizeNeeded=true,draggedUntil=0;

function render(){if(!sheet||sheet.hidden)return;const E=root.CoveResortEngine,g=api.game(),s=E.init(g),i=s.selected,c=s.cottages[i],z=E.stats(c),next=E.STAGES[c.stage+1];

const sig=JSON.stringify([panelMode,s.view,i,g.shells,s.completedStays,c.stage,c.bed,c.kind,c.built,c.guest?.party.name,s.amenities,s.businesses,c.job,c.style,c.service]);if(sig===signature)return;signature=sig;

if(panelMode.startsWith('place:')){renderPlace(panelMode.slice(6),s);return;}
const wasInside=sheet.classList.contains('rs-inside');sheet.classList.toggle('rs-inside',s.view==='inside');if(wasInside!==(s.view==='inside'))resizeNeeded=true;sheet.querySelector('.rs-zoom').hidden=s.view==='inside';sheet.querySelector('.rs-outside').hidden=s.view!=='inside';sheet.querySelector('.rs-wallet').textContent=Math.floor(g.shells)+' Shells';sheet.querySelector('.rs-map-label').textContent=s.view==='inside'?'Inside cottage '+(i+1):'Sixteen plots. One little coastal escape.';

sheet.classList.toggle('rs-panel-open',!!panelMode);sheet.classList.toggle('rs-amenities-only',panelMode==='amenities');const info=sheet.querySelector('.rs-chrome');info.innerHTML=`<span class="rs-kicker rs-property">${c.built?'YOUR RESORT':'ROOM TO GROW'}</span><h3>${c.built?E.BUILDINGS[c.kind].name:root.CoveResortScene.slots[i].name}</h3><p>${c.built?'Guests arrive, rest and check out automatically. Expand beds and accommodation to support more local businesses.':'A furnished cottage, ready for its first visitors. Open it and the resort looks after each stay.'}</p><div class="rs-summary">Level ${c.stage+1} · ${E.STAGES[c.stage].name}<br>${s.cottages.filter(x=>x.built).length} / 16 plots open · ${s.completedStays} stays<br>${s.revenue} Shells earned</div>`;

function button(label,action,disabled=false){const b=document.createElement('button');b.className='btn';b.textContent=label;b.disabled=disabled;b.onclick=()=>{action();api.save();signature='';render();draw();};info.append(b);}

if(c.built&&!c.job){const cv=document.createElement('canvas');cv.className='rs-mini rs-property';cv.width=640;cv.height=400;cv.setAttribute('aria-label','Inside this accommodation');info.append(cv);}
if(c.job){const p=document.createElement('p');p.textContent='Under renovation · Closed to guests until work finishes.';info.append(p);progress(info,c.job);}else if(!c.built){for(const [kind,building]of Object.entries(E.BUILDINGS)){const cost=E.buildCost(g,i,kind);button(building.name+' · '+(cost?cost.toLocaleString()+' Shells':'Free')+(s.cottages.some(c=>c.built||c.job)?' · '+(kind==='villa'?60:kind==='lodge'?30:10)+' min':''),()=>E.buildCottage(g,i,Date.now(),kind),g.shells<cost);}const options=document.createElement('p');options.textContent='Cottages start small. Family lodges host more guests. Terrace villas earn more per guest.';info.append(options);if(!s.cottages.some(c=>c.built||c.job)){const p=document.createElement('p');p.textContent='Start on any plot. Your first garden cottage is free and opens immediately.';info.append(p);}}

else{if(s.view==='inside')button('Back to resort map',()=>{s.view='outside';panelMode='';});const p=document.createElement('p');p.className='rs-income';p.textContent=z.capacity+' guest'+(z.capacity>1?'s':'')+' · '+Math.floor(z.payout*z.capacity*(1+E.bonus(g)))+' Shells per stay · '+Math.round(z.stayMs/1000)+' seconds';info.append(p);if(next)button('Upgrade cottage · '+next.cost+' Shells',()=>E.upgradeCottage(g,i),g.shells<next.cost);if(c.bed<2)button('Upgrade beds · '+120*(c.bed+1)+' Shells',()=>E.upgradeBed(g,i),g.shells<120*(c.bed+1));}

if(c.built&&!c.job){for(const [service,label] of [['family','Family rooms: +1 guest, +60 sec stays'],['retreat','Quiet retreat: +15 per guest, +30 sec stays'],['standard','Standard rooms']])button(label+' · 600 Shells · 15 min',()=>E.specialize(g,i,service),g.shells<600||(c.service||'standard')===service);const tip=document.createElement('p');tip.textContent='Renovations close this property immediately. Existing guests leave without a checkout payout. New rates apply after reopening. Roof colours are free.';info.append(tip);for(const style of ['sage','terracotta','ocean'])button('Roof · '+style,()=>E.customize(g,i,style),c.style===style);}

Array.from(info.children).forEach(el=>el.classList.add('rs-property'));const amenities=document.createElement('h4');amenities.textContent='Resort amenities';info.append(amenities);for(const amenity of E.AMENITIES){button(s.amenities[amenity.id]?amenity.name+' · Open':amenity.name+' · '+amenity.cost+' Shells',()=>E.buyAmenity(g,amenity.id),!!s.amenities[amenity.id]||!s.cottages.some(c=>c.built)||g.shells<amenity.cost);}const benefit=document.createElement('small');benefit.textContent='Amenities add '+Math.round(E.bonus(g)*100)+'% to new guest bookings. Garden +5% · Pool +10% · Café +15%.';info.append(benefit);

for(const b of E.BUSINESSES){const v=s.businesses[b.id];const h=document.createElement('h4');h.textContent=b.name+' · Level '+(v?.level||0);info.append(h);const p=document.createElement('p');p.textContent='Full demand: '+(b.gross-b.expense)+' net Shells / 5 min per level (sales '+b.gross+', supplies '+b.expense+'). Current: '+E.businessRate(g,b)+'. Needs '+b.need+' open properties. More beds bring more customers.';info.append(p);if(v?.job)progress(info,v.job);else if((v?.level||0)<3)button('Build / expand · '+b.cost*((v?.level||0)+1)+' Shells · '+b.minutes*((v?.level||0)+1)+' min',()=>E.buyBusiness(g,b.id),g.shells<b.cost*((v?.level||0)+1)||s.cottages.filter(c=>c.built).length<b.need);}

if(api.cafe)button('Enter Catmint Café',()=>{root.CoveResortView.stop();sheet.hidden=true;api.cafe();});if(api.garden)button('Enter Cove Garden',()=>{root.CoveResortView.stop();sheet.hidden=true;api.garden();});const note=document.createElement('small');note.textContent='Guests keep checking in while you are away, for up to 8 hours. No manual cleaning or check-in.';info.append(note);updateProgress();

Array.from(info.children).filter(el=>!el.classList.contains('rs-property')).forEach(el=>el.classList.add('rs-amenity'));const dismiss=document.createElement('button');dismiss.className='rs-dismiss';dismiss.textContent='Close';dismiss.onclick=()=>{panelMode='';signature='';render();};info.prepend(dismiss);const plots=sheet.querySelector('.rs-plots');plots.hidden=s.view==='inside';plots.querySelectorAll('button:not(.rs-destination)').forEach((b,j)=>{b.setAttribute('aria-pressed',String(panelMode==='property'&&j===i));b.setAttribute('aria-label',(s.cottages[j].built?'Inspect':'Open')+' cottage '+(j+1));});}

function draw(){if(!sheet||sheet.hidden||document.hidden)return;const cv=sheet.querySelector('canvas');if(resizeNeeded){const r=cv.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2,Math.sqrt(3000000/Math.max(1,r.width*r.height)));if(!r.width||!r.height)return;cv.width=Math.round(r.width*dpr);cv.height=Math.round(r.height*dpr);resizeNeeded=false;}const ctx=cv.getContext('2d');ctx.setTransform(cv.width/960,0,0,cv.height/640,0,0);const s=root.CoveResortEngine.init(api.game());root.CoveResortScene(ctx,{view:s.view,cottages:s.cottages,selected:s.view==='inside'||panelMode==='property'?s.selected:-1,amenities:s.amenities,businesses:s.businesses,t:matchMedia('(prefers-reduced-motion: reduce)').matches?0:performance.now(),a:api});drawMini(s);}


function renderPlace(id,s){
const E=root.CoveResortEngine,b=E.BUSINESSES.find(b=>b.id===id),v=s.businesses[id],names={reception:'Reception',cafe:'Catmint Café',garden:'Cove Garden',pool:'Lagoon pool'};
sheet.classList.add('rs-panel-open');sheet.classList.remove('rs-amenities-only','rs-inside');const info=sheet.querySelector('.rs-chrome');info.replaceChildren();
const close=document.createElement('button');close.className='rs-dismiss';close.textContent='Close';close.onclick=()=>{panelMode='';signature='';render();};info.append(close);
const h=document.createElement('h3');h.textContent=b?.name||names[id];info.append(h);
const cv=document.createElement('canvas');cv.className='rs-mini';cv.width=640;cv.height=400;cv.setAttribute('aria-label',h.textContent+' interior preview');info.append(cv);
const p=document.createElement('p');p.textContent=id==='reception'?s.cottages.filter(c=>c.guest).length+' occupied properties · '+s.completedStays+' completed stays. Guests check in automatically.':b?'Level '+(v?.level||0)+' · '+E.businessRate(api.game(),b)+' net Shells / 5 min':id==='pool'?'A place for guests to swim and unwind.':id==='garden'?'Grow ingredients for your café.':'Coffee, treats and a seat in the shade.';info.append(p);
function action(label,fn,disabled=false){const el=document.createElement('button');el.className='btn';el.textContent=label;el.disabled=disabled;el.onclick=()=>{fn();api.save();signature='';render();};info.append(el);}
if(v?.job)progress(info,v.job);else if(b&&(v?.level||0)<3){const cost=b.cost*((v?.level||0)+1);action('Build / expand · '+cost+' Shells · '+b.minutes*((v?.level||0)+1)+' min',()=>E.buyBusiness(api.game(),id),api.game().shells<cost||s.cottages.filter(c=>c.built).length<b.need);}
if(['cafe','garden'].includes(id)&&api[id])action('Enter '+names[id],()=>{root.CoveResortView.stop();sheet.hidden=true;api[id]();});
if(['pool','cafe','garden'].includes(id)&&!s.amenities[id]){const amenity=E.AMENITIES.find(a=>a.id===id);action('Open resort amenity · '+amenity.cost+' Shells',()=>E.buyAmenity(api.game(),id),api.game().shells<amenity.cost||!s.cottages.some(c=>c.built));}
sheet.querySelector('.rs-wallet').textContent=Math.floor(api.game().shells)+' Shells';updateProgress();
}
function drawMini(s){const cv=sheet.querySelector('.rs-mini');if(!cv)return;const c=cv.getContext('2d'),t=matchMedia('(prefers-reduced-motion: reduce)').matches?0:performance.now();
if(panelMode==='property'){c.setTransform(cv.width/960,0,0,cv.height/640,0,0);root.CoveResortScene(c,{view:'inside',cottages:s.cottages,selected:s.selected,t,a:api});return;}
const id=panelMode.slice(6),members=s.cottages.flatMap(p=>p.guest?.party?.members||[]),isOpen=id==='reception'||!!s.amenities[id]||!!s.businesses[id]?.level;
c.setTransform(2,0,0,2,0,0);c.fillStyle='#efe4cc';c.fillRect(0,0,320,200);c.fillStyle='#a3cbd0';c.fillRect(18,14,284,43);c.fillStyle='#82a591';c.fillRect(18,49,284,8);c.fillStyle='#d9bd91';c.fillRect(0,66,320,134);c.strokeStyle='#c1a47e';c.lineWidth=.6;for(let y=70;y<200;y+=12){c.beginPath();c.moveTo(0,y);c.lineTo(320,y);c.stroke();}
const box=(x,y,w,h,col)=>{c.fillStyle=col;c.fillRect(x,y,w,h);};
if(id==='pool'||id==='kayak'){box(20,76,280,106,'#68b6c6');c.strokeStyle='#def3df';for(let i=0;i<7;i++){c.beginPath();c.ellipse(150+Math.sin(t/1400+i)*12,85+i*14,100,3,0,0,Math.PI);c.stroke();}}
else if(id==='garden'){for(let i=0;i<6;i++){const x=32+i%3*95,y=83+Math.floor(i/3)*60;box(x,y,68,40,'#8b704f');for(let k=0;k<4;k++){c.fillStyle='#678753';c.beginPath();c.ellipse(x+10+k*15,y+17,7,11,0,0,7);c.fill();}}}
else{box(25,82,270,37,'#927653');box(22,77,276,8,'#f7e5ba');if(id==='reception'){for(let k=0;k<8;k++){box(220+k%4*15,60+Math.floor(k/4)*7,8,4,'#a78956');}box(43,64,32,13,'#f7edd5');c.fillStyle='#385949';c.font='7px Georgia';c.fillText('WELCOME',45,73);}else{box(235,52,38,25,'#638574');box(240,58,28,12,'#304d41');for(let i=0;i<6;i++){box(48+i*23,70,12,6,'#f0d29c');}}}
if(id==='reception')api.cat?.(c,{coatKey:'midknight',mascot:true,markSeed:777,age:'adult',pose:'loafing'},160,75,.65,t);
if(isOpen&&members.length){if(id==='reception'){for(let i=0;i<Math.min(4,members.length-1);i++){const phase=(t/9000)%1;api.cat?.(c,{...members[i+1],pose:'exploring'},102+i*42-phase*10,157+i%2*12,.65,t);}}else for(let i=0;i<Math.min(4,members.length);i++)api.cat?.(c,{...members[i],pose:id==='pool'?'loafing':'exploring'},48+i*72,148+Math.sin(t/1600+i)*5,.6,t);}
if(!isOpen){box(65,130,190,34,'#f5ebd4');c.fillStyle='#456351';c.textAlign='center';c.font='12px Georgia';c.fillText('Planned · not open yet',160,152);}
}

function progress(parent,job){const el=document.createElement('div');el.className='rs-progress';el.dataset.start=job.start;el.dataset.end=job.end;el.innerHTML='<progress max="1"></progress><small></small>';parent.append(el);}

function updateProgress(){sheet?.querySelectorAll('.rs-progress').forEach(el=>{const left=Math.max(0,+el.dataset.end-Date.now());el.querySelector('progress').value=1-left/(+el.dataset.end-+el.dataset.start);el.querySelector('small').textContent='Under renovation · '+Math.ceil(left/60000)+' min remaining';});}

root.CoveResortView={open(a){this.stop();api=a;if(!sheet){sheet=document.createElement('section');sheet.id='neo-resort';sheet.className='sheet neo-resort-screen';sheet.setAttribute('aria-label','Cove Resort');sheet.innerHTML='<header class="rs-top"><button class="btn rs-close">‹ Cove</button><div><span class="rs-kicker">A PLACE TO STAY</span><h2>Cove Resort</h2></div><span class="rs-wallet"></span></header><div class="rs-layout"><div class="rs-world"><p class="rs-map-label"></p><div class="rs-map-tools"><button class="btn rs-zoom">Zoom in</button><button class="btn rs-facilities">Amenities</button><button class="btn rs-outside" hidden>‹ Resort</button><span>Scroll to explore when zoomed</span></div><div class="rs-map-viewport"><div class="rs-scene-wrap"><canvas width="960" height="640" aria-label="Seaside resort map"></canvas><div class="rs-plots"></div></div></div><p class="rs-map-help">Tap a building to enter. Tap an empty plot to build.</p></div><aside class="rs-chrome" aria-live="polite"></aside></div>';document.getElementById('app').append(sheet);a.register(sheet);for(const [i,p] of root.CoveResortScene.slots.entries()){const b=document.createElement('button');b.style.cssText=`left:${p.x/9.6}%;top:${(p.y-12)/6.4}%;width:${p.w/9.6}%;height:${(p.h+20)/6.4}%`;b.onclick=()=>{if(performance.now()<draggedUntil)return;const s=root.CoveResortEngine.init(api.game());panelMode='property';s.selected=i;s.view='outside';api.save();signature='';render();draw();};sheet.querySelector('.rs-plots').append(b);}for(const [name,x,y,w,h,action] of [['Catmint Café',485,105,100,110,'cafe'],['Cove Garden',353,354,75,83,'garden'],['Reception',431,472,84,81,'reception'],['Lagoon pool',490,272,110,116,'pool'],...root.CoveResortEngine.BUSINESSES.map(b=>[b.name,b.x-30,b.y-35,65,80,b.id])]){const b=document.createElement('button');b.className='rs-destination';b.setAttribute('aria-label','Inspect '+name);b.title=name;b.style.cssText=`left:${x/9.6}%;top:${y/6.4}%;width:${w/9.6}%;height:${h/6.4}%`;b.onclick=()=>{if(performance.now()<draggedUntil)return;if((action==='cafe'||action==='garden')&&api[action]){root.CoveResortView.stop();sheet.hidden=true;api.save();api[action]();return;}panelMode='place:'+action;signature='';render();draw();};sheet.querySelector('.rs-plots').append(b);}

sheet.querySelector('.rs-facilities').onclick=()=>{panelMode=panelMode==='amenities'?'':'amenities';signature='';render();};sheet.querySelector('.rs-outside').onclick=()=>{root.CoveResortEngine.init(api.game()).view='outside';panelMode='';signature='';render();draw();};sheet.querySelector('.rs-zoom').onclick=()=>{const viewport=sheet.querySelector('.rs-map-viewport'),cx=(viewport.scrollLeft+viewport.clientWidth/2)/viewport.scrollWidth,cy=(viewport.scrollTop+viewport.clientHeight/2)/viewport.scrollHeight;const on=sheet.classList.toggle('rs-zoomed');sheet.querySelector('.rs-zoom').textContent=on?'Zoom out':'Zoom in';resizeNeeded=true;viewport.scrollLeft=cx*viewport.scrollWidth-viewport.clientWidth/2;viewport.scrollTop=cy*viewport.scrollHeight-viewport.clientHeight/2;draw();};const viewport=sheet.querySelector('.rs-map-viewport');let pointer=null;viewport.addEventListener('pointerdown',e=>{if(e.button!==0)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop,mouse:e.pointerType==='mouse',moved:false};});viewport.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(Math.hypot(dx,dy)>8){pointer.moved=true;draggedUntil=performance.now()+350;if(pointer.mouse){viewport.setPointerCapture(e.pointerId);viewport.scrollLeft=pointer.left-dx;viewport.scrollTop=pointer.top-dy;}}});const endPointer=()=>{if(pointer?.moved)draggedUntil=performance.now()+350;pointer=null;};viewport.addEventListener('pointerup',endPointer);viewport.addEventListener('pointercancel',endPointer);new ResizeObserver(()=>{resizeNeeded=true;}).observe(sheet.querySelector('canvas'));sheet.querySelector('.rs-close').onclick=()=>{this.stop();api.close();};}sheet.hidden=false;resizeNeeded=true;panelMode='';root.CoveResortEngine.init(a.game()).view='outside';signature='';root.CoveResortEngine.settle(a.game());a.save();render();draw();requestAnimationFrame(()=>{const v=sheet.querySelector('.rs-map-viewport');v.scrollLeft=(v.scrollWidth-v.clientWidth)/2;v.scrollTop=(v.scrollHeight-v.clientHeight)/2;});timer=setInterval(()=>{if(sheet.hidden){this.stop();return;}if(document.hidden)return;root.CoveResortEngine.settle(api.game());render();updateProgress();},1000);const tick=t=>{if(sheet.hidden)return;if(!document.hidden){draw();lastFrame=t;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);},stop(){clearInterval(timer);cancelAnimationFrame(frame);}};

})(globalThis);
